### ISSUE TITLE
NilObjectException when user clicks Cancel

### ISSUE THREAD

**Issue by stetch193** [stretch327/SOS-MacOSSaveOpenDialog#5]
Steps:

1. Open the example project
2. Locate the AddDelegates method
3. Comment out the following items
- obj.Callback_ShouldEnableItem = AddressOf NSSavePanel_ShouldEnableItem
- obj.Callback_DirectoryChanged = AddressOf NSSavePanel_DirectoryChanged
- obj.Callback_ShouldEnableItem = AddressOf NSSavePanel_ShouldEnableItem
- obj.Callback_UserEnteredFilename = AddressOf NSSavePanel_UserEnteredFilename
- obj.Callback_ValidateItem = AddressOf NSSavePanel_ValidateItem
- obj.Callback_WillExpand = AddressOf NSSavePanel_WillExpand
4. Run the application and press button 2
5. Select cancel

The following update seems to fix the issue:

```
Private Sub Response(value as integer)
  
  #If TargetMacOS
    
    If mDelegateCache <> nil Then  // Required when user presses cancel
      If mDelegateCache.HasKey(mPtr) Then
        mDelegateCache.Remove(mPtr)
      End If
    End if
    
...

End Sub
```

**Comment by stretch327** [comment]
Fixed.
